---
name: Ender2Pro-BlTouch
description: |
  BLTouch bracket for the Ender2 Pro

  ## Installation
  1. Remove the Z-Sense plug from the board
  1. Wire up the BLTouch to the 5 port header on main board
    The Brown and Black wires are both ground, you can join them to make wiring simpler
    I used a proper [JST from Amazon](https://www.amazon.com/dp/B06ZZ45G7G/ref=cm_sw_em_r_mt_dp_CYFAK1BVFZH8YKFFS9SW?_encoding=UTF8&psc=1)
  Marlin firmware should automatically detect the BLTouch.
  You will then need to calibrate the Z offset. On my machine the Z offset is -2.1mm 
license: 
  type: CC-Attribution # MIT, GPL, CC-Attribution, CC-Attribution-NoDerivs, CC-Attribution-ShareAlike, CC-Attribution-NonCommercial, CC-Attribution-NC-SA
  owner: Spencer Owen
  year: 2020
resources:
  4 Strand Wire: https://www.amazon.com/dp/B08JTZCJV1/ref=cm_sw_em_r_mt_dp_DV2TDB4MEC2DQNAGB2SA?_encoding=UTF8&psc=1
  JST Connector Kit: https://www.amazon.com/dp/B06ZZ45G7G/ref=cm_sw_em_r_mt_dp_CYFAK1BVFZH8YKFFS9SW?_encoding=UTF8&psc=1
# fusion_link: https://autodesk.example.com #comment out if no fusion link
links:
  # Thingiverse: https://www.thingiverse.com/thing:xxxx
  # Prusa: https://foo.com
  # GrabCad: https://foo.com
  # Hackster.io: https://hackster.io/foo
  # Hackaday: https://hackaday.io/foo
  # Reddit: https://www.reddit.com/r/foo
  # Github: https://github.com/foo
  # Blog: https://foo.com
