---
name: Ender2Pro-BlTouch
description: |
  BLTouch bracket for the Ender2 Pro

  ## Installation

  This should work with the M2.5 nuts/screws provided with the BLTouch _or_ you can use M3 screws (with no nuts).
  Note: When using M3 screws, you will be tapping directly into the plastic. It works well and that is how I installed mine

  1. Remove the Z-Sense plug from the board
  1. Wire up the BLTouch to the 5 port header on main board
    The Brown and Black wires are both ground, you can join them to make wiring simpler
    I used a proper [JST from Amazon](https://www.amazon.com/dp/B06ZZ45G7G/ref=cm_sw_em_r_mt_dp_CYFAK1BVFZH8YKFFS9SW?_encoding=UTF8&psc=1)
  Marlin firmware should automatically detect the BLTouch.
  You will then need to calibrate the Z offset. On my machine the Z offset is -2.1mm 

  Installing a BLTouch with this bracket will shift your X axis by 10mm. 
  Creality [has not yet released](https://github.com/Creality3DPrinting/Ender-3/issues/76) official configuration files so you can compile a new config. 
  Until they do you can modify the [reverse engineered configs from github](https://github.com/MarlinFirmware/Configurations/pull/633/files)

  ## Wiring
  ```
  - Blue -> White
  - Black -> Black/Brown
  - Green -> Yellow
  - Red -> Orange
  ```

license: 
  type: CC-Attribution # MIT, GPL, CC-Attribution, CC-Attribution-NoDerivs, CC-Attribution-ShareAlike, CC-Attribution-NonCommercial, CC-Attribution-NC-SA
  owner: Spencer Owen
  year: 2020
resources:
  4 Strand Wire: https://www.amazon.com/dp/B08JTZCJV1/ref=cm_sw_em_r_mt_dp_DV2TDB4MEC2DQNAGB2SA?_encoding=UTF8&psc=1
  JST Connector Kit: https://www.amazon.com/dp/B06ZZ45G7G/ref=cm_sw_em_r_mt_dp_CYFAK1BVFZH8YKFFS9SW?_encoding=UTF8&psc=1
# fusion_link: https://autodesk.example.com #comment out if no fusion link
links:
  Thingiverse: https://www.thingiverse.com/thing:5176711
  # Prusa: https://foo.com
  # GrabCad: https://foo.com
  # Hackster.io: https://hackster.io/foo
  # Hackaday: https://hackaday.io/foo
  # Reddit: https://www.reddit.com/r/foo
  Github: https://github.com/spuder/ender2pro-bltouch
  # Blog: https://foo.com
